[package]
name = "file-sharing"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version="1.44.2", features=["full"]}
libp2p = { version="0.55.0", features=["full", "gossipsub"]}
futures = "0.3.31"
regex = "1.11.1"
